server:
  port: 8881
  servlet:
    context-path: /con
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.12.71:61616
    pool:
      enabled: true
      max-connections: 10
  application:
    name: consumer

queueName: producer
topicName: producer.topic


