server:
  port: 8880
  servlet:
    context-path: /pro
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.12.71:61616
    pool:
      enabled: true
      max-connections: 10
  application:
    name: producer

queueName: producer
topicName: producer.topic


